### ISSUE TITLE
add to homebrew for installation 

### ISSUE THREAD

**Issue by AndrewSB** [mattrajca/sudo-touchid#10]
http://brew.sh

**Comment by rahul286** [comment]
I am on a slow internet connection, so can't download Xcode today. :-(

I wish this was distributed as a brew package.

**Comment by jonasrauber** [comment]
Are you planning to do this?

**Comment by RoySegall** [comment]
I don't have access to xcode since I'm not a developer so if we have any .dmg file or a script that would be awesome.

**Comment by evanmhm** [comment]
You can just get Xcode from the App Store without a developer account, but a brew package would be pretty cool.

**Comment by RoySegall** [comment]
I not familiar with the xCdoe environment so I'm struggling with this one. I did the build but where is the compiled file?

**Comment by einsteinx2** [comment]
@RoySegall If you look in the Products group on the left panel of Xcode you'll see it there, and you can right click it to show in finder.

However, the easiest way to build it is to just clone the repo, cd into the directory, run xcodebuild with no options, then the file will be in ./build/Release/sudo in that folder

**Comment by rahul286** [comment]
I managed to get it working using Xcode only.

Below are all commands I needed to run from start to end:

```
git clone https://github.com/mattrajca/sudo-touchid
cd sudo-touchid
xcodebuild 
cd build/Release
sudo chown root:wheel sudo && sudo chmod 4755 sudo
sudo cp - sudo /usr/local/bin
```

**Comment by jeremymlane** [comment]
@rahul286 I needed to do the following instead. Just the last two lines are different.

```
git clone https://github.com/mattrajca/sudo-touchid
cd sudo-touchid
xcodebuild 
cd build/Release
sudo cp sudo /usr/local/bin
sudo chown root:wheel /usr/local/bin/sudo && sudo chmod 4755 /usr/local/bin/sudo
```

**Comment by idoo** [comment]
@mattrajca do we have a chance to merge it?

**Comment by RoySegall** [comment]
Does running the homebrew commands in the commit will do the trick?

**Comment by idoo** [comment]
@RoySegall yep, you it just add custom formula to your brew
just run, and keep hope, that paulche didn't change that formula in future ;)
```
brew tap paulche/sudo-touchid
brew install sudo-touchid
```

**Comment by brunojdo** [comment]
Hi guys, I follow the homebrew method and broke my `sudo`. 
`sudo: /usr/local/bin/sudo must be owned by uid 0 and have the setuid bit set` 
To fix this problem I had to enable the Root user: [How to](https://support.apple.com/en-us/HT204012) and fix the permissions of sudo symlink `/usr/local/bin/sudo`. I execute the last command of @jeremymlane.

**Comment by rahul286** [comment]
@jeremymlane I thought

```
sudo cp ./sudo /usr/local/bin
sudo chown root:wheel /usr/local/bin/sudo && sudo chmod 4755 /usr/local/bin/sudo
```

will create a problem because `sudo` in the second line would be used from `/usr/local/bin/sudo`.

I tested your method and it did not create any problem.

**Comment by AFakeman** [comment]
```
anton  ~  brew tap paulche/sudo-touchid
anton  ~  brew install sudo-touchid
==> Installing sudo-touchid from paulche/sudo-touchid
==> Cloning https://github.com/mattrajca/sudo-touchid
Cloning into '/Users/anton/Library/Caches/Homebrew/sudo-touchid--git'...
remote: Counting objects: 632, done.
remote: Compressing objects: 100% (492/492), done.
remote: Total 632 (delta 102), reused 569 (delta 102), pack-reused 0
Receiving objects: 100% (632/632), 3.16 MiB | 1.97 MiB/s, done.
Resolving deltas: 100% (102/102), done.
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
==> xcodebuild
Error: undefined method `undent' for #<String:0x00007ffb740caab8>
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Taps/paulche/homebrew-sudo-touchid/sudo-touchid.rb:27:in `caveats'
/usr/local/Homebrew/Library/Homebrew/caveats.rb:17:in `caveats'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/forwardable.rb:202:in `empty?'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:610:in `caveats'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:659:in `finish'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:322:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:253:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:251:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:251:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'
```
